env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
  - plugin:import/typescript
  - plugin:import/warnings
  - plugin:import/errors
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - 'jest'
  - 'import'
rules:
  import/order:
    [2, { 'groups': ['builtin', 'external', 'parent', 'sibling', 'index'], 'alphabetize': { 'order': 'asc', 'caseInsensitive': true } }]
overrides:
  - files:
      - '*.test.ts'
    rules:
      'max-nested-callbacks': off
  - files:
      - '*.ts'
